import { supabase } from '@/lib/supabase'
import type { Treatment } from '@/types'

// Servicios reales de Clínica AestheticA (fuente: Booksy)
export const MOCK_TREATMENTS: Treatment[] = [
  // ── ESTÉTICA FACIAL ──────────────────────────────────────────────────────
  {
    id: 'f1',
    name: 'Limpieza Facial Básica',
    category: 'facial',
    description: 'Limpieza profunda con extracción de impurezas para piel fresca y equilibrada.',
    duration_min: 60,
    price_eur: 65,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f2',
    name: 'Hydroface Plus — Limpieza Profunda Avanzada',
    category: 'facial',
    description: 'Limpieza avanzada con hidrodermabrasión para una piel renovada y luminosa.',
    duration_min: 90,
    price_eur: 109,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f3',
    name: 'Microdermabrasión con Punta de Diamante',
    category: 'facial',
    description: 'Exfoliación mecánica que elimina células muertas y estimula la renovación celular.',
    duration_min: 60,
    price_eur: 54,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f4',
    name: 'Limpieza Facial Hombre con Microdermoabrasión',
    category: 'facial',
    description: 'Tratamiento adaptado a la piel masculina con limpieza y microdermoabrasión.',
    duration_min: 75,
    price_eur: 75,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f5',
    name: 'Facial Premium Maria Galland [Skin]Biosis',
    category: 'facial',
    description: 'Tratamiento de alta gama con la exclusiva tecnología [Skin]Biosis de Maria Galland.',
    duration_min: 90,
    price_eur: 129,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f6',
    name: 'Fotorejuvenecimiento LPL',
    category: 'facial',
    description: 'Luz pulsada de última generación para reducir manchas, rojeces y signos de envejecimiento.',
    duration_min: 50,
    price_eur: 110,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f7',
    name: 'Hollywood Peeling Láser ND-YAG',
    category: 'facial',
    description: 'Peeling de carbono con láser ND-YAG para poros dilatados, acné y luminosidad instantánea.',
    duration_min: 30,
    price_eur: 120,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f8',
    name: 'Radiofrecuencia con Vitaminas',
    category: 'facial',
    description: 'Combinación de radiofrecuencia y vitaminas para tensar y revitalizar la piel.',
    duration_min: 30,
    price_eur: 70,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f9',
    name: 'Radiofrecuencia con Mascarilla Alginato',
    category: 'facial',
    description: 'Radiofrecuencia reafirmante combinada con mascarilla de alginato calmante y nutritiva.',
    duration_min: 30,
    price_eur: 75,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f10',
    name: 'Hydro Kiss',
    category: 'facial',
    description: 'Tratamiento de hidratación intensa con ácido hialurónico para una piel jugosa y tersa.',
    duration_min: 90,
    price_eur: 55,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f11',
    name: 'Masaje Lifting Miofascial',
    category: 'facial',
    description: 'Técnica manual que trabaja el tejido miofascial para un efecto lifting natural.',
    duration_min: 30,
    price_eur: 40,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f12',
    name: 'Microneedling con Cóctel Vitamínico',
    category: 'facial',
    description: 'Microagujas que estimulan el colágeno e introducen activos en profundidad.',
    duration_min: 30,
    price_eur: 150,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f13',
    name: 'Peeling Dermatology Facial',
    category: 'facial',
    description: 'Peeling médico que renueva la piel y mejora manchas, acné y textura irregular.',
    duration_min: 30,
    price_eur: 90,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f14',
    name: 'Enzimoterapia',
    category: 'facial',
    description: 'Exfoliación enzimática suave que purifica y regenera sin agredir la piel sensible.',
    duration_min: 30,
    price_eur: 69,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f15',
    name: 'Carboxiterapia Facial',
    category: 'facial',
    description: 'Microinyecciones de CO₂ para mejorar la circulación, reducir ojeras y rejuvenecer.',
    duration_min: 30,
    price_eur: 55,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'f16',
    name: 'Presoterapia Ocular',
    category: 'facial',
    description: 'Masaje por presión en la zona ocular para drenar bolsas y reducir fatiga visual.',
    duration_min: 30,
    price_eur: 20,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  // ── ESTÉTICA CORPORAL ─────────────────────────────────────────────────────
  {
    id: 'c1',
    name: 'Presoterapia Terapéutica Alta Gama',
    category: 'corporal',
    description: 'Drenaje linfático por presión de alta gama para piernas cansadas y retención de líquidos.',
    duration_min: 30,
    price_eur: 25,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c2',
    name: 'Presoterapia Corporal y Ocular',
    category: 'corporal',
    description: 'Sesión combinada de presoterapia corporal y ocular para un drenaje completo.',
    duration_min: 30,
    price_eur: 30,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c3',
    name: 'Masaje Completo Integral (60 min)',
    category: 'corporal',
    description: 'Masaje integral de cuerpo completo que trabaja la musculatura y libera tensiones.',
    duration_min: 60,
    price_eur: 65,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c4',
    name: 'Masaje Completo Integral (90 min)',
    category: 'corporal',
    description: 'Versión extendida del masaje integral para una relajación muscular profunda.',
    duration_min: 90,
    price_eur: 75,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c5',
    name: 'Masaje Relajante con Aromaterapia',
    category: 'corporal',
    description: 'Masaje suave con aceites esenciales para reducir el estrés y mejorar el bienestar.',
    duration_min: 45,
    price_eur: 60,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c6',
    name: 'Abdomen de Acero Estándar',
    category: 'corporal',
    description: 'Tratamiento de tonificación abdominal con tecnología de electroestimulación.',
    duration_min: 60,
    price_eur: 50,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c7',
    name: 'Abdomen de Acero Premium',
    category: 'corporal',
    description: 'Sesión premium de tonificación abdominal de mayor duración y mayor intensidad.',
    duration_min: 90,
    price_eur: 60,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c8',
    name: 'Body Sculpture con Presoterapia',
    category: 'corporal',
    description: 'Modelado corporal que combina tecnología reductora con drenaje linfático.',
    duration_min: 80,
    price_eur: 80,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c9',
    name: 'Mesoterapia Corporal',
    category: 'corporal',
    description: 'Microinyecciones con activos lipolíticos para reducir celulitis y grasa localizada.',
    duration_min: 30,
    price_eur: 55,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'c10',
    name: 'Peeling Corporal con Hidratación',
    category: 'corporal',
    description: 'Exfoliación corporal seguida de hidratación intensa para una piel suave y uniforme.',
    duration_min: 75,
    price_eur: 50,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  // ── DEPILACIÓN LÁSER ─────────────────────────────────────────────────────
  {
    id: 'l1',
    name: 'Depilación Láser (zona)',
    category: 'laser',
    description: 'Depilación definitiva por zonas con tecnología láser de última generación.',
    duration_min: 30,
    price_eur: 119,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'l2',
    name: 'Depilación Láser Diodo — Mujer Cuerpo Completo',
    category: 'laser',
    description: 'Sesión de depilación láser de diodo para cuerpo completo, la solución más eficaz.',
    duration_min: 45,
    price_eur: 599,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'l3',
    name: 'Depilación Láser Diodo — Hombre Cuerpo Completo',
    category: 'laser',
    description: 'Depilación láser de diodo adaptada a la piel y el vello masculino, cuerpo completo.',
    duration_min: 60,
    price_eur: 699,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'l4',
    name: 'Depilación con LPL Luz Pulsada',
    category: 'laser',
    description: 'Luz pulsada de alta eficacia para reducción progresiva del vello en todo tipo de zonas.',
    duration_min: 30,
    price_eur: 55,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  // ── ESTÉTICA CAPILAR ─────────────────────────────────────────────────────
  {
    id: 'cap1',
    name: 'Mesoterapia Capilar (bono 12 sesiones)',
    category: 'capilar',
    description: 'Bono de 12 sesiones de mesoterapia capilar para frenar la caída y densificar el cabello.',
    duration_min: 90,
    price_eur: 950,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  // ── PAQUETES ESPECIALES ───────────────────────────────────────────────────
  {
    id: 'b1',
    name: 'Bono Futura Mamá',
    category: 'bienestar',
    description: 'Tratamiento especialmente diseñado para el bienestar de la mamá durante el embarazo.',
    duration_min: 90,
    price_eur: 75,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'b2',
    name: 'Pack Belleza para Novias — Estándar',
    category: 'bienestar',
    description: 'Pack completo de tratamientos para que la novia luzca perfecta en su gran día.',
    duration_min: 30,
    price_eur: 499,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'b3',
    name: 'Pack Belleza para Novias — Premium',
    category: 'bienestar',
    description: 'Versión premium del pack nupcial con tratamientos exclusivos de mayor profundidad.',
    duration_min: 90,
    price_eur: 699,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'b4',
    name: 'Momento de Bienestar para Dos',
    category: 'bienestar',
    description: 'Experiencia de relajación compartida, ideal para regalar o disfrutar en pareja.',
    duration_min: 45,
    price_eur: 99,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'b5',
    name: 'Ritual de Relax para Dos',
    category: 'bienestar',
    description: 'Ritual de bienestar extendido para dos personas con masaje y tratamiento facial.',
    duration_min: 105,
    price_eur: 199,
    is_active: true,
    image_url: null,
    created_at: '',
  },
  {
    id: 'b6',
    name: 'Tarjeta de Regalo',
    category: 'bienestar',
    description: 'Regala una experiencia única en Clínica AestheticA a quien más quieras.',
    duration_min: 60,
    price_eur: 60,
    is_active: true,
    image_url: null,
    created_at: '',
  },
]

export const fetchTreatments = async (): Promise<Treatment[]> => {
  const { data, error } = await supabase
    .from('treatments')
    .select('*')
    .eq('is_active', true)
    .order('category')

  if (error) {
    console.warn('[treatmentService] Supabase no disponible, usando mock data:', error.message)
    return MOCK_TREATMENTS
  }

  return (data as Treatment[]) ?? MOCK_TREATMENTS
}
